### ISSUE TITLE
[Question] - Is it possible to use Jest as Test Runner? 

### ISSUE THREAD

**Issue by saif-shines** [coderoad/coderoad-cli#84]
Maintainers,

Thanks for building a great project. I really appreciate it, and I am exploring if this can be something I could invest in and adopt.

I see test runner _coderoad_ uses is mocha.

Does coderoad CLI(or may be VS Code extension) recognize only `mocha`? Can I use `jest`? For example, features to Jest's snapshot testing is one feature that can be complimentary for tutorials use cases.

**Comment by saif-shines** [comment]
Meanwhile I'd try,

```yaml
...
 testRunner:
    command: ./node_modules/.bin/jest
    args:
      tap: --reporter=mocha-tap-reporter
    directory: coderoad
...
```
